use StudentManagement;

INSERT INTO news (title, content, description, created_at, user_id) VALUES
('Handheld emperor', 
 '# Handheld emperor\n\nNintendo, a Japanese electronics company, started as a [hanafuda cards](https://en.wikipedia.org/wiki/Hanafuda) manufacturer in 1889. In the mid-1970s, they entered the early video games market and became famous for their home video and handheld game consoles. Nintendo introduced consoles like the **NES**, **SNES**, and **Wii**. But the most revolutionary was for sure the **Game Boy**.\n\n## A countdown of Nintendo handhelds\n\n![The Nintendo "flagship" - handheld Game Boy](https://ckeditor.com/docs/ckeditor5/latest/assets/img/game_boy.jpg)\n\n1. **Game & Watch** was Nintendo''s first product offering out-of-home gaming. From 1980 to 1991, over a hundred games were released, gaining great popularity.\n2. In 1989, the original **Game Boy** was released. The new amazing machine utilized a cartridge system, allowing the users to play a multitude of games of all kinds. This was a historical game-changer.\n   - It was followed by a number of versions, such as Game Boy Color or Game Boy Advance.\n3. In 2004, Nintendo introduced a new console family called the **Nintendo DS**. It sported a dual LCD screen in a folded shell, with the lower one being a touchscreen.\n   - The most prominent development was Nintendo 3DS, which offered a 3D display.\n4. 2017 brought the hybrid experience for both couch-preferring gamers and handheld enthusiasts with the release of the **Nintendo Switch**. It offers both a TV mode with high-definition graphics and a handheld mode using the built-in 6.2" display.\n\n## Handheld consoles'' popularity\n\nWhile the most recent Switch is a prevalent choice nowadays, the 2DS and 3DS consoles are still popular. The king, however, is none other than the original wonder — the Game Boy.\n\n| Console          | Production dates   | Pieces sold (2021) |\n|------------------|--------------------|---------------------|\n| Game & Watch     | 1980-1991, 2020-2021| 44 million          |\n| Game Boy         | 1989-2010          | 201 million         |\n| Nintendo DS      | 2011-2020          | 76 million          |\n| Switch           | since 2017         | 140 million         |\n\n*As of early 2024.*\n\n## Handheld gaming experience\n\n> It''s dangerous to go alone! Take this.  \n> *The Legend of Zelda, 1986*\n\nGames offered by Nintendo include multiple genres, out of which the famous platformer arcade *Super Mario* and the adventure role-play *Legend of Zelda* series are probably the most iconic.\n\n### Games that can be played on the handheld family include:\n\n- Action & adventure games\n  - The *Legend of Zelda* series\n  - *Chrono Trigger*\n- First-person action games\n  - *Splatoon*\n- Role-playing games (RPG)\n  - The *Pokémon* series\n  - The *Final Fantasy* series', 
 'An overview of Nintendo handhelds and their impact on gaming.', 
 GETDATE(), 
 7),

('The Rise of Mobile Gaming', 
 '# The Rise of Mobile Gaming\n\nThe mobile gaming industry has exploded in recent years, driven by advances in smartphone technology and an ever-growing user base. Mobile games like Angry Birds, Fortnite, and Among Us have reshaped the landscape of gaming, allowing players to enjoy high-quality experiences on the go.\n\n## A timeline of mobile gaming:\n\n1. In 1997, the Snake game debuted on Nokia phones, laying the groundwork for mobile gaming.\n2. The launch of the App Store in 2008 revolutionized the industry, providing a platform for developers to distribute games.\n3. In 2012, Angry Birds became a cultural phenomenon, showcasing the potential of mobile gaming.\n4. By 2020, mobile gaming revenues surpassed those of PC and console gaming combined, highlighting its dominance in the gaming market.\n\n## Mobile gaming today:\n\nThe mobile gaming sector continues to grow, with innovations in augmented reality (AR) and virtual reality (VR) paving the way for new experiences. Games like Pokémon GO have popularized AR, bringing players into the real world with their favorite characters.\n\n## The future of mobile gaming:\n\nWith the rise of 5G technology and cloud gaming, the future looks bright for mobile gaming. As players continue to demand high-quality experiences, developers are likely to innovate further, making gaming more accessible than ever before.', 
 'A look at the evolution and future of mobile gaming.', 
 GETDATE(), 
 7),

('The Evolution of Home Consoles', 
 '# The Evolution of Home Consoles\n\nHome consoles have come a long way since their inception in the early 1970s. Companies like Atari, Sega, and Sony have played pivotal roles in shaping the home gaming experience, with consoles that continue to push technological boundaries.\n\n## A timeline of console evolution:\n\n1. In 1972, the Magnavox Odyssey was released as the first home console, featuring simple graphics and gameplay.\n2. The Atari 2600 launched in 1977, popularizing cartridge-based gaming and introducing iconic titles like Space Invaders.\n3. In 1985, the Nintendo Entertainment System (NES) revived the gaming market, featuring memorable franchises such as Super Mario Bros.\n4. Fast forward to 2000, when the PlayStation 2 became the best-selling console of all time, offering DVD playback and a robust library of games.\n\n## Current state of home consoles:\n\nToday’s consoles, including the PlayStation 5 and Xbox Series X, offer breathtaking graphics and immersive gameplay experiences. With the addition of online multiplayer and digital marketplaces, the way we game has changed dramatically.\n\n## The future of home consoles:\n\nWith advancements in cloud gaming and virtual reality, home consoles are expected to evolve further, providing players with unprecedented experiences and connectivity.', 
 'A historical overview of home consoles and their impact on gaming.', 
 GETDATE(), 
 7),

('The Impact of Esports', 
 '# The Impact of Esports\n\nEsports has transformed the gaming industry, turning competitive gaming into a multi-billion-dollar sector. Major tournaments attract millions of viewers, while professional players and teams gain recognition similar to traditional sports.\n\n## A brief history of esports:\n\n1. The first known video game competition took place in 1972, featuring Spacewar!.\n2. In 1997, the Red Annihilation tournament for Quake offered a Ferrari as a prize, attracting media attention.\n3. The launch of Twitch in 2011 revolutionized how esports events are streamed and consumed.\n4. By the late 2010s, esports had become a billion-dollar industry, with professional leagues and sponsorships emerging across various games.\n\n## The current esports landscape:\n\nToday, games like League of Legends, Dota 2, and Counter-Strike: Global Offensive dominate the competitive scene. These titles feature tournaments with prize pools reaching millions of dollars, showcasing the skill and strategy of professional players.\n\n## The future of esports:\n\nAs esports continues to gain recognition, it is expected to expand further, potentially becoming an Olympic event. With growing audiences and increasing investments, the future of esports looks bright.', 
 'An exploration of the rise and significance of esports in modern gaming.', 
 GETDATE(), 
 7);

